name: (STAGING) build, deploy in Vercel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: deploy to Vercel
        id: branch_deploy_vercel
        run: URL=$(npx vercel --prod --confirm -n ${{ secrets.PROJECT_ID }} -t ${{ secrets.TRIPS_APP_FRONT_TOKEN }} --scope ${{ secrets.ORG_ID }} -b DEPLOY_ENV=staging -b REACT_APP_API_URL=${{ secrets.API_URL_STAGING }} -e DEPLOY_ENV=staging -e REACT_APP_API_URL=${{ secrets.API_URL_STAGING }}
#        npx vercel --prod --confirm -n ${{ secrets.PROJECT_ID }} -t {{ secrets.TRIPS_APP_FRONT_TOKEN }} --scope ${{ secrets.ORG_ID }} -b DEPLOY_ENV=staging -b REACT_APP_API_URL=${{ secrets.API_URL_STAGING }} -e DEPLOY_ENV=staging -e REACT_APP_API_URL=${{ secrets.API_URL_STAGING }}  
      

